COUNTRIES = ['Andorra', 'United Arab Emirates', 'Afghanistan', 'Albania', 'Armenia', 'Angola', 'Argentina', 'Austria', 'Australia', 'Azerbaijan', 'Bosnia & Herzegovina', 'Bangladesh', 'Belgium', 'Burkina Faso', 'Bulgaria', 'Bahrain', 'Burundi', 'Benin', 'Bermuda', 'Brunei', 'Bolivia', 'Brazil', 'Bahamas', 'Bhutan', 'Botswana', 'Belarus', 'Belize', 'Canada', 'Central African Republic', 'Switzerland', 'Côte d’Ivoire', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cyprus', 'Czechia', 'Germany', 'Denmark', 'Dominica', 'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Western Sahara', 'Spain', 'Ethiopia', 'France', 'Gabon', 'United Kingdom', 'Georgia', 'Ghana', 'Gibraltar', 'Greenland', 'Gambia', 'Guinea', 'Equatorial Guinea', 'Greece', 'Guatemala', 'Guam', 'Guinea-Bissau', 'Guyana', 'Hong Kong', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'Isle of Man', 'India', 'Iraq', 'Iran', 'Iceland', 'Italy', 'Jersey', 'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia', 'Kiribati', 'Comoros', 'St. Kitts & Nevis', 'South Korea', 'Kuwait', 'Cayman Islands', 'Kazakhstan', 'Laos',
             'Lebanon', 'St. Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco', 'Monaco', 'Moldova', 'Montenegro', 'St. Martin', 'Madagascar', 'North Macedonia', 'Mali', 'Myanmar', 'Mongolia', 'Macao', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia', 'Mozambique', 'Namibia', 'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'Niue', 'New Zealand', 'Oman', 'Panama', 'Peru', 'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'Puerto Rico', 'Palestine', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Romania', 'Serbia', 'Russia', 'Rwanda', 'Saudi Arabia', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'Slovenia', 'Slovakia', 'Sierra Leone', 'Senegal', 'Somalia', 'South Sudan', 'São Tomé & Príncipe', 'El Salvador', 'Sint Maarten', 'Syria', 'Eswatini', 'Chad', 'Togo', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Tunisia', 'Tonga', 'Turkey', 'Trinidad & Tobago', 'Tuvalu', 'Taiwan', 'Tanzania', 'Ukraine', 'Uganda', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Samoa', 'Kosovo', 'Yemen', 'South Africa', 'Zambia', 'Zimbabwe']

FLAGS = {
    '🇦🇩': 'Andorra',
    '🇦🇪': 'United Arab Emirates',
    '🇦🇫': 'Afghanistan',
    '🇦🇱': 'Albania',
    '🇦🇲': 'Armenia',
    '🇦🇴': 'Angola',
    '🇦🇷': 'Argentina',
    '🇦🇹': 'Austria',
    '🇦🇺': 'Australia',
    '🇦🇿': 'Azerbaijan',
    '🇧🇦': 'Bosnia & Herzegovina',
    '🇧🇩': 'Bangladesh',
    '🇧🇪': 'Belgium',
    '🇧🇫': 'Burkina Faso',
    '🇧🇬': 'Bulgaria',
    '🇧🇭': 'Bahrain',
    '🇧🇮': 'Burundi',
    '🇧🇯': 'Benin',
    '🇧🇲': 'Bermuda',
    '🇧🇳': 'Brunei',
    '🇧🇴': 'Bolivia',
    '🇧🇷': 'Brazil',
    '🇧🇸': 'Bahamas',
    '🇧🇹': 'Bhutan',
    '🇧🇼': 'Botswana',
    '🇧🇾': 'Belarus',
    '🇧🇿': 'Belize',
    '🇨🇦': 'Canada',
    '🇨🇫': 'Central African Republic',
    '🇨🇭': 'Switzerland',
    '🇨🇮': 'Côte d’Ivoire',
    '🇨🇱': 'Chile',
    '🇨🇲': 'Cameroon',
    '🇨🇳': 'China',
    '🇨🇴': 'Colombia',
    '🇨🇷': 'Costa Rica',
    '🇨🇺': 'Cuba',
    '🇨🇾': 'Cyprus',
    '🇨🇿': 'Czechia',
    '🇩🇪': 'Germany',
    '🇩🇰': 'Denmark',
    '🇩🇲': 'Dominica',
    '🇩🇴': 'Dominican Republic',
    '🇩🇿': 'Algeria',
    '🇪🇨': 'Ecuador',
    '🇪🇪': 'Estonia',
    '🇪🇬': 'Egypt',
    '🇪🇭': 'Western Sahara',
    '🇪🇸': 'Spain',
    '🇪🇹': 'Ethiopia',
    '🇫🇷': 'France',
    '🇬🇦': 'Gabon',
    '🇬🇧': 'United Kingdom',
    '🇬🇪': 'Georgia',
    '🇬🇭': 'Ghana',
    '🇬🇮': 'Gibraltar',
    '🇬🇱': 'Greenland',
    '🇬🇲': 'Gambia',
    '🇬🇳': 'Guinea',
    '🇬🇶': 'Equatorial Guinea',
    '🇬🇷': 'Greece',
    '🇬🇹': 'Guatemala',
    '🇬🇺': 'Guam',
    '🇬🇼': 'Guinea-Bissau',
    '🇬🇾': 'Guyana',
    '🇭🇰': 'Hong Kong',
    '🇭🇳': 'Honduras',
    '🇭🇷': 'Croatia',
    '🇭🇹': 'Haiti',
    '🇭🇺': 'Hungary',
    '🇮🇩': 'Indonesia',
    '🇮🇪': 'Ireland',
    '🇮🇱': 'Israel',
    '🇮🇲': 'Isle of Man',
    '🇮🇳': 'India',
    '🇮🇶': 'Iraq',
    '🇮🇷': 'Iran',
    '🇮🇸': 'Iceland',
    '🇮🇹': 'Italy',
    '🇯🇪': 'Jersey',
    '🇯🇲': 'Jamaica',
    '🇯🇴': 'Jordan',
    '🇯🇵': 'Japan',
    '🇰🇪': 'Kenya',
    '🇰🇬': 'Kyrgyzstan',
    '🇰🇭': 'Cambodia',
    '🇰🇮': 'Kiribati',
    '🇰🇲': 'Comoros',
    '🇰🇳': 'St. Kitts & Nevis',
    '🇰🇷': 'South Korea',
    '🇰🇼': 'Kuwait',
    '🇰🇾': 'Cayman Islands',
    '🇰🇿': 'Kazakhstan',
    '🇱🇦': 'Laos',
    '🇱🇧': 'Lebanon',
    '🇱🇨': 'St. Lucia',
    '🇱🇮': 'Liechtenstein',
    '🇱🇰': 'Sri Lanka',
    '🇱🇷': 'Liberia',
    '🇱🇸': 'Lesotho',
    '🇱🇹': 'Lithuania',
    '🇱🇺': 'Luxembourg',
    '🇱🇻': 'Latvia',
    '🇱🇾': 'Libya',
    '🇲🇦': 'Morocco',
    '🇲🇨': 'Monaco',
    '🇲🇩': 'Moldova',
    '🇲🇪': 'Montenegro',
    '🇲🇫': 'St. Martin',
    '🇲🇬': 'Madagascar',
    '🇲🇰': 'North Macedonia',
    '🇲🇱': 'Mali',
    '🇲🇲': 'Myanmar',
    '🇲🇳': 'Mongolia',
    '🇲🇴': 'Macao',
    '🇲🇹': 'Malta',
    '🇲🇺': 'Mauritius',
    '🇲🇻': 'Maldives',
    '🇲🇼': 'Malawi',
    '🇲🇽': 'Mexico',
    '🇲🇾': 'Malaysia',
    '🇲🇿': 'Mozambique',
    '🇳🇦': 'Namibia',
    '🇳🇨': 'New Caledonia',
    '🇳🇪': 'Niger',
    '🇳🇬': 'Nigeria',
    '🇳🇮': 'Nicaragua',
    '🇳🇱': 'Netherlands',
    '🇳🇴': 'Norway',
    '🇳🇵': 'Nepal',
    '🇳🇷': 'Nauru',
    '🇳🇺': 'Niue',
    '🇳🇿': 'New Zealand',
    '🇴🇲': 'Oman',
    '🇵🇦': 'Panama',
    '🇵🇪': 'Peru',
    '🇵🇬': 'Papua New Guinea',
    '🇵🇭': 'Philippines',
    '🇵🇰': 'Pakistan',
    '🇵🇱': 'Poland',
    '🇵🇷': 'Puerto Rico',
    '🇵🇸': 'Palestine',
    '🇵🇹': 'Portugal',
    '🇵🇼': 'Palau',
    '🇵🇾': 'Paraguay',
    '🇶🇦': 'Qatar',
    '🇷🇴': 'Romania',
    '🇷🇸': 'Serbia',
    '🇷🇺': 'Russia',
    '🇷🇼': 'Rwanda',
    '🇸🇦': 'Saudi Arabia',
    '🇸🇨': 'Seychelles',
    '🇸🇩': 'Sudan',
    '🇸🇪': 'Sweden',
    '🇸🇬': 'Singapore',
    '🇸🇮': 'Slovenia',
    '🇸🇰': 'Slovakia',
    '🇸🇱': 'Sierra Leone',
    '🇸🇳': 'Senegal',
    '🇸🇴': 'Somalia',
    '🇸🇸': 'South Sudan',
    '🇸🇹': 'São Tomé & Príncipe',
    '🇸🇻': 'El Salvador',
    '🇸🇽': 'Sint Maarten',
    '🇸🇾': 'Syria',
    '🇸🇿': 'Eswatini',
    '🇹🇩': 'Chad',
    '🇹🇬': 'Togo',
    '🇹🇭': 'Thailand',
    '🇹🇯': 'Tajikistan',
    '🇹🇲': 'Turkmenistan',
    '🇹🇳': 'Tunisia',
    '🇹🇴': 'Tonga',
    '🇹🇷': 'Turkey',
    '🇹🇹': 'Trinidad & Tobago',
    '🇹🇻': 'Tuvalu',
    '🇹🇼': 'Taiwan',
    '🇹🇿': 'Tanzania',
    '🇺🇦': 'Ukraine',
    '🇺🇬': 'Uganda',
    '🇺🇸': 'United States',
    '🇺🇾': 'Uruguay',
    '🇺🇿': 'Uzbekistan',
    '🇻🇪': 'Venezuela',
    '🇻🇳': 'Vietnam',
    '🇼🇸': 'Samoa',
    '🇽🇰': 'Kosovo',
    '🇾🇪': 'Yemen',
    '🇿🇦': 'South Africa',
    '🇿🇲': 'Zambia',
    '🇿🇼': 'Zimbabwe',
}
